# Suspicious keywords in URLs
SUSPICIOUS_KEYWORDS = ["login", "verify", "secure", "account", "update"]
SUSPICIOUS_TLDS = ["xyz", "top", "click", "info"]
# URL scoring
URL_KEYWORD_SCORE = 1
DOMAIN_MISMATCH_SCORE = 2
NEW_DOMAIN_SCORE = 2
LOOKALIKE_DOMAIN_SCORE = 2
URL_TLDS_SCORE = 1

URL_MALICIOUS_THRESHOLD = 3

# Risk scoring
RISK_URL = 15
RISK_SPOOFING = 10
RISK_HEADER = 10
RISK_NEW_DOMAIN = 5
RISK_IDENTITY = 20
RISK_ATTACHMENT = 15

LONG_URL = 2


ATTACH_EXECUTABLE_SCORE = 40
ATTACH_MACRO_SCORE = 30
ATTACH_ARCHIVE_SCORE = 20
ATTACH_PDF_SCORE = 10
ATTACH_DOUBLE_EXT_SCORE = 25
ATTACH_HASH_REPUTATION_SCORE = 50

ATTACH_MALICIOUS_THRESHOLD = 40